<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pilih_foto_dari_galeri</name>
   <tag></tag>
   <elementGuidId>efeb46e5-17c1-4465-84d5-c0178160bd77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//android.widget.ImageView)[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
